---
- name: Install Java 1.7 and some basic dependencies
  yum: name={{ item }} state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    
  with_items:
   - unzip
   - java-1.7.0-openjdk
   
- name: Install Java 1.7 and some basic dependencies
  apt: pkg={{ item }} state=present update_cache=yes  
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  with_items:
   - unzip
#   - openjdk-7-jdk
# openjdk-7-jdk is not longer available for this ubuntu version
   - openjdk-8-jdk

- name: Create directory for Jboss build
  file: path=/opt/ state=directory mode=0755
    
- name: Download JBoss from jboss.org
  get_url: url={{ jboss_url }} dest=/opt/{{ jboss_archive }}

- name: Extract archive
  command: chdir=/usr/share /usr/bin/unzip -q /opt/{{ jboss_archive }} creates={{ jboss_base_dir }}

- name: Rename install directory
  command: chdir=/usr/share /bin/mv {{ jboss_archive_extracted }} jboss-as creates={{ jboss_base_dir }}

- name: Copying standalone.xml configuration file
  template: src=standalone.xml dest={{ jboss_base_dir }}/standalone/configuration/
  #template: src=standalone.xml dest={{ jboss_base_dir }}/server/jbossweb-standalone/conf/
  notify: restart jboss

- name: Add group "{{ jboss_group }}"
  group: name={{ jboss_group }}

- name: Add user "{{ jboss_owner }}"
  user: name={{ jboss_owner }} group={{ jboss_group }} home={{ jboss_base_dir }} shell={{ jboss_shell }} comment="Jboss User" 

- name: Change ownership of JBoss installation
  file: path={{ jboss_base_dir }}/ owner={{ jboss_owner }} group={{ jboss_group }} state=directory recurse=yes

- name: Copy the init script
  copy: src=jboss-as-standalone-{{ ansible_distribution }}.sh dest=/etc/init.d/jboss mode=0755

#- name: Enable JBoss to be started at boot
#  service: name=jboss enabled=yes state=started

- name: checking the jboss web link status
  uri:
     url="http://localhost:{{ jboss_http_port }}/health/health.html"
     return_content=yes
  register: webpage
  ignore_errors: True

- name: fail or pass status
  fail:
  when: "'OK' not in webpage.content"

#- name: deploy iptables rules
#  template: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables
