---
- name: Ensure Java is installed.
  apt: "name={{ item }} state=present"
  with_items: "{{ java_packages }}"

- name: Update cache
  apt: state=present update_cache=yes

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home="{{ tomcat_home_dir }}" createhome=yes

- name: download and unarchive tomcat
  unarchive: src="{{ tomcat_web_url }}" dest="{{ tomcat_home_dir }}" copy=no

- name: Change ownership of Tomcat installation
  file: path="{{ tomcat_home_dir }}" owner=tomcat group=tomcat state=directory recurse=yes

  
- name: configure Tomcat conf dir permissions
  file:
    path: "{{ tomcat_home_dir }}/{{ tomcat_version }}/conf"
    state: directory
    recurse: yes
    mode: "g+r,g+x"

- name: changing ownership for all dirs
  command: chown -R tomcat "{{ tomcat_home_dir }}/{{ tomcat_version }}"

- name: Defining tomcat service for systemd
  file: src=tomcat.service dest=/etc/systemd/system mode=0755
  notify: reload tomcat service

- name: checking the tomcat web link status
  uri:
     url="http://localhost:{{ tomcat_http_port }}"
     return_content=yes
  register: webpage
  ignore_errors: True

- name: fail or pass status
  fail:
  when: "'Apache Tomcat/8.5.11' not in webpage.content" 
